appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: QanXxuultW/utsXCVgah7r5NrfCMGvdu9ANDOospoLa/gUiGsFGPIWyOn+g2uMwXEUQXUWxgRw6vbP/KWEC3zmvEKb9DrqBVYtvCMVgDwMCBO5c+C/EcKQb2s9cEF5wwpxVJnsRnNoBJH5pYgm4qE8nVlt1n4U9u/CxlLS5kd4nMJHddrKsImUkdSo4d1BDzuFGpwl8k8M0MDbCaLXLz0tzNAe/BEGAwV53hfosX2VqeKOW77YTd8EgwKhdbZIM2iKUTpxt+efWrDUyqavPHWsGO5eeCil217chV7ml+Eu/85OP65mdV+3CL74yfdPHDTNooAIT3HxJrcce5zGwQ2LTbYqJAvJ4HVWwj6kXwXwS/JyWNLa7aDLFOHV5VUv0CrVxVIe9RRz4Fl6645nSjN005BDHqGiJQmTgEAQVdec4GeHuTMW7o3xonTjHvs2E4qGE/cblixRxx7QgiyEpH0vwYysMho0BWBggaeu1PUTstz573ysGK05PRvX7MQg3QR1OZ4CuCVmBTB/UJCiFlA4J7gfIX8VwJunYIVIaABAjFJbWM8XcOghc2XKod/VLW09ks0a7YWGFmfEHD4VXMIKoukr4W7BAGaNNY+Ch0eO/N1JbJoFBdiX8SVaEkeuFuOZkVijfWOChD8XcSWQcs+cX5jMyTP0rrWLEWhwhy0tY=
